export enum EnvKey {
  ENV = 'ENV',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  STAFF_CHECK_IN_SUMMARY_CALCULATION_CRON_TIME = 'STAFF_CHECK_IN_SUMMARY_CALCULATION_CRON_TIME',
}
