export enum EnvKey {
  ENV = 'ENV',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  STAFF_STORE_CHECKIN_INFO_CRON_TIME = 'STAFF_STORE_CHECKIN_INFO_CRON_TIME',
  STAFF_EXPORT_CHECKIN_INFO_DAILY = 'STAFF_EXPORT_CHECKIN_INFO_DAILY',

  GOOGLE_WORKSPACE_CREDENTIALS_FILE_NAME = 'GOOGLE_WORKSPACE_CREDENTIALS_FILE_NAME',
}
